### ISSUE TITLE
Soul Drain bugged

### ISSUE THREAD

**Issue by efrixes** [nerthul11/CombatRandomizer#1]
I have a run using the Soul Drain setting set the the default Standard difficulty, and I have found both Soul Plugs that are added to the loot pool. According to the setting description, this should disable the Soul Drain curse effect, but it's still draining ever so slightly, at a rate that I probably wouldn't have easily noticed except for the fact that I can't ever maintain a completely full soul container.

The Soul Drain effect also seems to be interfering in allowing Soul Vessels to fill up the main container, rendering them mostly useless.

**Comment by efrixes** [comment]
An update/edit/correction:
After playing some more with it, I no longer believe the Soul Meter is actually draining. It _is_ still incapable of maintaining visually the graphic that indicates the Soul Meter is full. The Soul Vessels seem to be drawn from for a brief moment right after load transitions, but almost immediately stop functioning again.

**Comment by nerthul11** [comment]
This should be fixed on the current version.
